export default {
  baidu: [
    { value: 'auto', label: '自动检测语言' },
    { value: 'zh', label: '简体中文' },
    { value: 'en', label: '英语' },
    { value: 'yue', label: '粤语' },
    { value: 'wyw', label: '文言文' },
    { value: 'jp', label: '日语' },
    { value: 'fra', label: '法语' },
    { value: 'spa', label: '西班牙语' },
    { value: 'th', label: '泰语' },
    { value: 'ara', label: '阿拉伯语' },
    { value: 'ru', label: '俄语' },
    { value: 'pt', label: '葡萄牙语' },
    { value: 'de', label: '德语' },
    { value: 'it', label: '意大利语' },
    { value: 'el', label: '希腊语' },
    { value: 'nl', label: '荷兰语' },
    { value: 'pl', label: '波兰语' },
    { value: 'bul', label: '保加利亚语' },
    { value: 'est', label: '爱沙尼亚语' },
    { value: 'dan', label: '丹麦语' },
    { value: 'fin', label: '芬兰语' },
    { value: 'cs', label: '捷克语' },
    { value: 'rom', label: '罗马尼亚语' },
    { value: 'slo', label: '斯洛文尼亚语' },
    { value: 'swe', label: '瑞典语' },
    { value: 'hu', label: '匈牙利语' },
    { value: 'cht', label: '繁体中文' },
    { value: 'vie', label: '越南语' }
  ],
  tencent: [
    { value: 'auto', label: '自动检测语言' },
    { value: 'zh', label: '简体中文' },
    { value: 'zh-TW', label: '繁体中文' },
    { value: 'en', label: '英语' },
    { value: 'ja', label: '日语' },
    { value: 'ko', label: '韩语' },
    { value: 'fr', label: '法语' },
    { value: 'es', label: '西班牙语' },
    { value: 'it', label: '意大利语' },
    { value: 'de', label: '德语' },
    { value: 'tr', label: '土耳其语' },
    { value: 'ru', label: '俄语' },
    { value: 'pt', label: '葡萄牙语' },
    { value: 'vi', label: '越南语' },
    { value: 'id', label: '印尼语' },
    { value: 'th', label: '泰语' },
    { value: 'ms', label: '马来西亚语' },
    { value: 'ar', label: '阿拉伯语' },
    { value: 'hi', label: '印地语' }
  ],
  xunfei: [
    { value: 'cn', label: '汉语普通话' },
    { value: 'en', label: '英语' },
    { value: 'ii', label: '彝语' },
    { value: 'yue', label: '广东话' },
    { value: 'ja', label: '日语' },
    { value: 'ru', label: '俄语' },
    { value: 'fr', label: '法语' },
    { value: 'es', label: '西班牙语' },
    { value: 'ar', label: '阿拉伯语' },
    { value: 'it', label: '意大利语' },
    { value: 'tr', label: '土耳其语' },
    { value: 'vi', label: '越南语' },
    { value: 'th', label: '泰语' },
    { value: 'ko', label: '韩语' },
    { value: 'de', label: '德语' },
    { value: 'kka', label: '哈萨克语' },
    { value: 'af', label: '南非荷兰语' },
    { value: 'am', label: '阿姆哈拉语' },
    { value: 'az', label: '阿塞拜疆语' },
    { value: 'bn', label: '孟加拉语' },
    { value: 'ca', label: '加泰罗尼亚语' },
    { value: 'cs', label: '捷克语' },
    { value: 'da', label: '丹麦语' },
    { value: 'el', label: '希腊语' },
    { value: 'fa', label: '波斯语' },
    { value: 'fi', label: '芬兰语' },
    { value: 'he', label: '希伯来语' },
    { value: 'hi', label: '印地语' },
    { value: 'hr', label: '克罗地亚语' },
    { value: 'hu', label: '匈牙利语' },
    { value: 'hy', label: '亚美尼亚语' },
    { value: 'id', label: '印尼语' },
    { value: 'is', label: '冰岛语' },
    { value: 'tl', label: '塔加路语（菲律宾）' },
    { value: 'ro', label: '罗马尼亚语' },
    { value: 'ka', label: '格鲁吉亚语' },
    { value: 'km', label: '高棉语' },
    { value: 'lo', label: '老挝语' },
    { value: 'lt', label: '立陶宛语' },
    { value: 'lv', label: '拉脱维亚语' },
    { value: 'ml', label: '马拉雅拉姆语' },
    { value: 'mr', label: '马拉地语' },
    { value: 'nb', label: '博克马尔挪威语' },
    { value: 'ne', label: '尼泊尔语' },
    { value: 'nl', label: '荷兰语' },
    { value: 'pl', label: '波兰语' },
    { value: 'pt', label: '葡萄牙语' },
    { value: 'si', label: '僧伽罗语' },
    { value: 'sk', label: '斯洛伐克语' },
    { value: 'sl', label: '斯洛文尼亚语' },
    { value: 'sr', label: '塞尔维亚语' },
    { value: 'su', label: '巽他语' },
    { value: 'sv', label: '瑞典语' },
    { value: 'sw', label: '斯瓦希里语' },
    { value: 'ta', label: '泰米尔语' },
    { value: 'te', label: '泰卢固语' },
    { value: 'jv', label: '爪哇语' },
    { value: 'ms', label: '马来语' },
    { value: 'uk', label: '乌克兰语' },
    { value: 'ur', label: '乌尔都语' },
    { value: 'zu', label: '南非祖鲁语' },
    { value: 'mn', label: '内蒙语' },
    { value: 'my', label: '缅甸语' },
    { value: 'nm', label: '外蒙语' },
    { value: 'ps', label: '普什图语' },
    { value: 'ha', label: '豪萨语' },
    { value: 'uz', label: '乌兹别克语' },
    { value: 'tk', label: '土库曼语' },
    { value: 'tg', label: '塔吉克语' },
    { value: 'bg', label: '保加利亚语' }
  ],
  youdao: [
    { label: '自动检测语言', value: 'auto' },
    { label: '简体中文', value: 'zh-CHS' },
    { label: '阿拉伯语', value: 'ar' },
    { label: '德语', value: 'de' },
    { label: '英语', value: 'en' },
    { label: '西班牙语', value: 'es' },
    { label: '法语', value: 'fr' },
    { label: '印地语', value: 'hi' },
    { label: '印度尼西亚语', value: 'id' },
    { label: '意大利语', value: 'it' },
    { label: '日语', value: 'ja' },
    { label: '韩语', value: 'ko' },
    { label: '荷兰语', value: 'nl' },
    { label: '葡萄牙语', value: 'pt' },
    { label: '俄语', value: 'ru' },
    { label: '泰语', value: 'th' },
    { label: '越南语', value: 'vi' },
    { label: '繁体中文', value: 'zh-CHT' },
    { label: '南非荷兰语', value: 'af' },
    { label: '阿姆哈拉语', value: 'am' },
    { label: '阿塞拜疆语', value: 'az' },
    { label: '白俄罗斯语', value: 'be' },
    { label: '保加利亚语', value: 'bg' },
    { label: '孟加拉语', value: 'bn' },
    { label: '波斯尼亚语', value: 'bs' },
    { label: '加泰隆语', value: 'ca' },
    { label: '宿务语', value: 'ceb' },
    { label: '科西嘉语', value: 'co' },
    { label: '捷克语', value: 'cs' },
    { label: '威尔士语', value: 'cy' },
    { label: '丹麦语', value: 'da' },
    { label: '希腊语', value: 'el' },
    { label: '世界语', value: 'eo' },
    { label: '爱沙尼亚语', value: 'et' },
    { label: '巴斯克语', value: 'eu' },
    { label: '波斯语', value: 'fa' },
    { label: '芬兰语', value: 'fi' },
    { label: '斐济语', value: 'fj' },
    { label: '弗里西语', value: 'fy' },
    { label: '爱尔兰语', value: 'ga' },
    { label: '苏格兰盖尔语', value: 'gd' },
    { label: '加利西亚语', value: 'gl' },
    { label: '古吉拉特语', value: 'gu' },
    { label: '豪萨语', value: 'ha' },
    { label: '夏威夷语', value: 'haw' },
    { label: '希伯来语', value: 'he' },
    { label: '印地语', value: 'hi' },
    { label: '克罗地亚语', value: 'hr' },
    { label: '海地克里奥尔语', value: 'ht' },
    { label: '匈牙利语', value: 'hu' },
    { label: '亚美尼亚语', value: 'hy' },
    { label: '伊博语', value: 'ig' },
    { label: '冰岛语', value: 'is' },
    { label: '爪哇语', value: 'jw' },
    { label: '格鲁吉亚语', value: 'ka' },
    { label: '哈萨克语', value: 'kk' },
    { label: '高棉语', value: 'km' },
    { label: '卡纳达语', value: 'kn' },
    { label: '库尔德语', value: 'ku' },
    { label: '柯尔克孜语', value: 'ky' },
    { label: '拉丁语', value: 'la' },
    { label: '卢森堡语', value: 'lb' },
    { label: '老挝语', value: 'lo' },
    { label: '立陶宛语', value: 'lt' },
    { label: '拉脱维亚语', value: 'lv' },
    { label: '马尔加什语', value: 'mg' },
    { label: '毛利语', value: 'mi' },
    { label: '马其顿语', value: 'mk' },
    { label: '马拉雅拉姆语', value: 'ml' },
    { label: '蒙古语', value: 'mn' },
    { label: '马拉地语', value: 'mr' },
    { label: '马来语', value: 'ms' },
    { label: '马耳他语', value: 'mt' },
    { label: '白苗语', value: 'mww' },
    { label: '缅甸语', value: 'my' },
    { label: '尼泊尔语', value: 'ne' },
    { label: '荷兰语', value: 'nl' },
    { label: '挪威语', value: 'no' },
    { label: '齐切瓦语', value: 'ny' },
    { label: '克雷塔罗奥托米语', value: 'otq' },
    { label: '旁遮普语', value: 'pa' },
    { label: '波兰语', value: 'pl' },
    { label: '普什图语', value: 'ps' },
    { label: '罗马尼亚语', value: 'ro' },
    { label: '信德语', value: 'sd' },
    { label: '僧伽罗语', value: 'si' },
    { label: '斯洛伐克语', value: 'sk' },
    { label: '斯洛文尼亚语', value: 'sl' },
    { label: '萨摩亚语', value: 'sm' },
    { label: '修纳语', value: 'sn' },
    { label: '索马里语', value: 'so' },
    { label: '阿尔巴尼亚语', value: 'sq' },
    { label: '塞尔维亚语(西里尔文)', value: 'sr-Cyrl' },
    { label: '塞尔维亚语(拉丁文)', value: 'sr-Latn' },
    { label: '塞索托语', value: 'st' },
    { label: '巽他语', value: 'su' },
    { label: '瑞典语', value: 'sv' },
    { label: '斯瓦希里语', value: 'sw' },
    { label: '泰米尔语', value: 'ta' },
    { label: '泰卢固语', value: 'te' },
    { label: '塔吉克语', value: 'tg' },
    { label: '菲律宾语', value: 'tl' },
    { label: '克林贡语', value: 'tlh' },
    { label: '汤加语', value: 'to' },
    { label: '土耳其语', value: 'tr' },
    { label: '塔希提语', value: 'ty' },
    { label: '乌克兰语', value: 'uk' },
    { label: '乌尔都语', value: 'ur' },
    { label: '乌兹别克语', value: 'uz' },
    { label: '南非科萨语', value: 'xh' },
    { label: '意第绪语', value: 'yi' },
    { label: '约鲁巴语', value: 'yo' },
    { label: '尤卡坦玛雅语', value: 'yua' },
    { label: '粤语', value: 'yue' },
    { label: '南非祖鲁语', value: 'zu' }
  ],
  ali: [
    {label: '自动检测语言', value: 'auto'},
    {label: '中文', value: 'zh'},
    {label: '英语', value: 'en'},
    {label: '阿布哈兹语', value: 'ab'},
    {label: '阿尔巴尼亚语', value: 'sq'},
    {label: '阿肯语', value: 'ak'},
    {label: '阿拉伯语', value: 'ar'},
    {label: '阿拉贡语', value: 'an'},
    {label: '阿姆哈拉语', value: 'am'},
    {label: '阿萨姆语', value: 'as'},
    {label: '阿塞拜疆语', value: 'az'},
    {label: '阿斯图里亚斯语', value: 'ast'},
    {label: '阿兹特克语', value: 'nch'},
    {label: '埃维语', value: 'ee'},
    {label: '艾马拉语', value: 'ay'},
    {label: '爱尔兰语', value: 'ga'},
    {label: '爱沙尼亚语', value: 'et'},
    {label: '奥杰布瓦语', value: 'oj'},
    {label: '奥克语', value: 'oc'},
    {label: '奥里亚语', value: 'or'},
    {label: '奥罗莫语', value: 'om'},
    {label: '奥塞梯语', value: 'os'},
    {label: '巴布亚皮钦语', value: 'tpi'},
    {label: '巴什基尔语', value: 'ba'},
    {label: '巴斯克语', value: 'eu'},
    {label: '白俄罗斯语', value: 'be'},
    {label: '柏柏尔语', value: 'ber'},
    {label: '班巴拉语', value: 'bm'},
    {label: '邦阿西楠语', value: 'pag'},
    {label: '保加利亚语', value: 'bg'},
    {label: '北萨米语', value: 'se'},
    {label: '本巴语', value: 'bem'},
    {label: '比林语', value: 'byn'},
    {label: '比斯拉马语', value: 'bi'},
    {label: '俾路支语', value: 'bal'},
    {label: '冰岛语', value: 'is'},
    {label: '波兰语', value: 'pl'},
    {label: '波斯尼亚语', value: 'bs'},
    {label: '波斯语', value: 'fa'},
    {label: '博杰普尔语', value: 'bho'},
    {label: '布列塔尼语', value: 'br'},
    {label: '查莫罗语', value: 'ch'},
    {label: '查瓦卡诺语', value: 'cbk'},
    {label: '楚瓦什语', value: 'cv'},
    {label: '聪加语', value: 'ts'},
    {label: '鞑靼语', value: 'tt'},
    {label: '丹麦语', value: 'da'},
    {label: '掸语', value: 'shn'},
    {label: '德顿语', value: 'tet'},
    {label: '德语', value: 'de'},
    {label: '低地德语', value: 'nds'},
    {label: '低地苏格兰语', value: 'sco'},
    {label: '迪维西语', value: 'dv'},
    {label: '侗语', value: 'kdx'},
    {label: '杜順語', value: 'dtp'},
    {label: '俄语', value: 'ru'},
    {label: '法罗语', value: 'fo'},
    {label: '法语', value: 'fr'},
    {label: '梵语', value: 'sa'},
    {label: '菲律宾语', value: 'fil'},
    {label: '斐济语', value: 'fj'},
    {label: '芬兰语', value: 'fi'},
    {label: '弗留利语', value: 'fur'},
    {label: '富尔语', value: 'fvr'},
    {label: '刚果语', value: 'kg'},
    {label: '高棉语', value: 'km'},
    {label: '格雷罗纳瓦特尔语', value: 'ngu'},
    {label: '格陵兰语', value: 'kl'},
    {label: '格鲁吉亚语', value: 'ka'},
    {label: '格罗宁根方言', value: 'gos'},
    {label: '古吉拉特语', value: 'gu'},
    {label: '瓜拉尼语', value: 'gn'},
    {label: '哈萨克语', value: 'kk'},
    {label: '海地克里奥尔语', value: 'ht'},
    {label: '韩语', value: 'ko'},
    {label: '豪萨语', value: 'ha'},
    {label: '荷兰语', value: 'nl'},
    {label: '黑山语', value: 'cnr'},
    {label: '胡帕语', value: 'hup'},
    {label: '基里巴斯语', value: 'gil'},
    {label: '基隆迪语', value: 'rn'},
    {label: '基切语', value: 'quc'},
    {label: '吉尔吉斯斯坦语', value: 'ky'},
    {label: '加利西亚语', value: 'gl'},
    {label: '加泰罗尼亚语', value: 'ca'},
    {label: '捷克语', value: 'cs'},
    {label: '卡拜尔语', value: 'kab'},
    {label: '卡纳达语', value: 'kn'},
    {label: '卡努里语', value: 'kr'},
    {label: '卡舒比语', value: 'csb'},
    {label: '卡西语', value: 'kha'},
    {label: '康沃尔语', value: 'kw'},
    {label: '科萨语', value: 'xh'},
    {label: '科西嘉语', value: 'co'},
    {label: '克里克语', value: 'mus'},
    {label: '克里米亚鞑靼语', value: 'crh'},
    {label: '克林贡语', value: 'tlh'},
    {label: '克罗地亚语', value: 'hbs'},
    {label: '克丘亚语', value: 'qu'},
    {label: '克什米尔语', value: 'ks'},
    {label: '库尔德语', value: 'ku'},
    {label: '拉丁语', value: 'la'},
    {label: '拉特加莱语', value: 'ltg'},
    {label: '拉脱维亚语', value: 'lv'},
    {label: '老挝语', value: 'lo'},
    {label: '立陶宛语', value: 'lt'},
    {label: '林堡语', value: 'li'},
    {label: '林加拉语', value: 'ln'},
    {label: '卢干达语', value: 'lg'},
    {label: '卢森堡语', value: 'lb'},
    {label: '卢森尼亚语', value: 'rue'},
    {label: '卢旺达语', value: 'rw'},
    {label: '罗马尼亚语', value: 'ro'},
    {label: '罗曼什语', value: 'rm'},
    {label: '罗姆语', value: 'rom'},
    {label: '逻辑语', value: 'jbo'},
    {label: '马达加斯加语', value: 'mg'},
    {label: '马恩语', value: 'gv'},
    {label: '马耳他语', value: 'mt'},
    {label: '马拉地语', value: 'mr'},
    {label: '马拉雅拉姆语', value: 'ml'},
    {label: '马来语', value: 'ms'},
    {label: '马里语（俄罗斯）', value: 'chm'},
    {label: '马其顿语', value: 'mk'},
    {label: '马绍尔语', value: 'mh'},
    {label: '玛雅语', value: 'kek'},
    {label: '迈蒂利语', value: 'mai'},
    {label: '毛里求斯克里奥尔语', value: 'mfe'},
    {label: '毛利语', value: 'mi'},
    {label: '蒙古语', value: 'mn'},
    {label: '孟加拉语', value: 'bn'},
    {label: '缅甸语', value: 'my'},
    {label: '苗语', value: 'hmn'},
    {label: '姆班杜语', value: 'umb'},
    {label: '纳瓦霍语', value: 'nv'},
    {label: '南非语', value: 'af'},
    {label: '尼泊尔语', value: 'ne'},
    {label: '纽埃语', value: 'niu'},
    {label: '挪威语', value: 'no'},
    {label: '帕姆语', value: 'pmn'},
    {label: '帕皮阿门托语', value: 'pap'},
    {label: '旁遮普语', value: 'pa'},
    {label: '葡萄牙语', value: 'pt'},
    {label: '普什图语', value: 'ps'},
    {label: '齐切瓦语', value: 'ny'},
    {label: '契维语', value: 'tw'},
    {label: '切罗基语', value: 'chr'},
    {label: '日语', value: 'ja'},
    {label: '瑞典语', value: 'sv'},
    {label: '萨摩亚语', value: 'sm'},
    {label: '桑戈语', value: 'sg'},
    {label: '僧伽罗语', value: 'si'},
    {label: '上索布语', value: 'hsb'},
    {label: '世界语', value: 'eo'},
    {label: '斯洛文尼亚语', value: 'sl'},
    {label: '斯瓦希里语', value: 'sw'},
    {label: '索马里语', value: 'so'},
    {label: '斯洛伐克语', value: 'sk'},
    {label: '他加禄语', value: 'tl'},
    {label: '塔吉克语', value: 'tg'},
    {label: '塔希提语', value: 'ty'},
    {label: '泰卢固语', value: 'te'},
    {label: '泰米尔语', value: 'ta'},
    {label: '泰语', value: 'th'},
    {label: '汤加语（汤加群岛）', value: 'to'},
    {label: '汤加语（赞比亚）', value: 'toi'},
    {label: '提格雷尼亚语', value: 'ti'},
    {label: '图瓦卢语', value: 'tvl'},
    {label: '图瓦语', value: 'tyv'},
    {label: '土耳其语', value: 'tr'},
    {label: '土库曼语', value: 'tk'},
    {label: '瓦隆语', value: 'wa'},
    {label: '瓦瑞语（菲律宾）', value: 'war'},
    {label: '威尔士语', value: 'cy'},
    {label: '文达语', value: 've'},
    {label: '沃拉普克语', value: 'vo'},
    {label: '沃洛夫语', value: 'wo'},
    {label: '乌德穆尔特语', value: 'udm'},
    {label: '乌尔都语', value: 'ur'},
    {label: '乌孜别克语', value: 'uz'},
    {label: '西班牙语', value: 'es'},
    {label: '西方国际语', value: 'ie'},
    {label: '西弗里斯兰语', value: 'fy'},
    {label: '西里西亚语', value: 'szl'},
    {label: '希伯来语', value: 'he'},
    {label: '希利盖农语', value: 'hil'},
    {label: '夏威夷语', value: 'haw'},
    {label: '现代希腊语', value: 'el'},
    {label: '新共同语言', value: 'lfn'},
    {label: '信德语', value: 'sd'},
    {label: '匈牙利语', value: 'hu'},
    {label: '修纳语', value: 'sn'},
    {label: '宿务语', value: 'ceb'},
    {label: '叙利亚语', value: 'syr'},
    {label: '巽他语', value: 'su'},
    {label: '亚美尼亚语', value: 'hy'},
    {label: '亚齐语', value: 'ace'},
    {label: '伊班语', value: 'iba'},
    {label: '伊博语', value: 'ig'},
    {label: '伊多语', value: 'io'},
    {label: '伊洛卡诺语', value: 'ilo'},
    {label: '伊努克提图特语', value: 'iu'},
    {label: '意大利语', value: 'it'},
    {label: '意第绪语', value: 'yi'},
    {label: '因特语', value: 'ia'},
    {label: '印地语', value: 'hi'},
    {label: '印度尼西亚语', value: 'id'},
    {label: '印古什语', value: 'inh'},
    {label: '约鲁巴语', value: 'yo'},
    {label: '越南语', value: 'vi'},
    {label: '扎扎其语', value: 'zza'},
    {label: '爪哇语', value: 'jv'},
    {label: '中文繁体', value: 'zh-tw'},
    {label: '中文粤语', value: 'yue'},
    {label: '祖鲁语', value: 'zu'}
  ]
};